### ISSUE TITLE
复制里面的"authorization"和"x-guest-token"信息

### ISSUE THREAD

**Issue by yeStwind** [DengChenlong-Studio/TwitterCrawler#1]
你好，未找到"x-guest-token"字段，确定是这个名字吗？

**Comment by ChenlongDeng** [comment]
![WechatIMG35](https://user-images.githubusercontent.com/50456848/161048882-db87b793-f5a9-4e10-aa3d-e0d038171a85.png)
2022.03.31测试，仍然可以找到该字段。
